<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <title>BLOG</title>
    <link href='/resources/views/style.css' rel='stylesheet' type='text/css'>
    <style>


        .blok {
            border-radius: 4px;
            box-shadow: rgba(0, 0, 0, 1.2) 0px 1px 3px;
            position: absolute;
            right: 0;
            top: 40px;
            width: 25%;
            background: rgba(126, 126, 126, 0.49);
            height: 480px;
            padding: 5px;
            text-align: center;
        }
    </style>
</head>
<body>
<ul id="navbar">
    <li><a href="/">Главная</a></li>

    <?php if ($_SESSION['user']['role'] == 'admin') : ?>
        <li><a href="/new">Добавить</a></li>
    <? endif; ?>

    <?php if ($_SESSION['user']) : ?>
        <li><a href="/session/destroy">Выход</a></li>
    <? else : ?>
        <li><a href="/session/new">Вход</a></li>
    <? endif; ?>
</ul>

<div class="wrapper-article">
    <?php foreach ($articles as $article) : ?>

        <div class="article">
            <h2><a href="articles/<?= $article['id'] ?>"><?= $article['title'] ?></a></h2>

            <?php if (!empty($article['image'])) : ?>
                <div class="image">
                    <img src="../resources/<?= $article['image']; ?>"
                         align="left" width=100% height=100%>
                </div>
            <? endif ?>

            <div>
                <?= strlen(strip_tags($article['content'])) >
                strlen(mb_substr(strip_tags($article['content']), 0, 300)) ?
                    mb_substr(strip_tags($article['content']), 0, 300) . '...' :
                    mb_substr(strip_tags($article['content']), 0, 300) ?>
            </div>

        </div>
    <?php endforeach ?>
</div>


<div class="blok">
    <h3>Посты недели</h3>
    <?php foreach ($variables['articlesTop'] as $article) : ?>
        <p><a href="articles/<?= $article['id'] ?>"><?= $article['title'] ?></a></p>
    <?php endforeach ?>
</div>
</body>
</html>